// Auto-generated mapping from catalog exercise IDs to ExerciseDB GIF URLs
// Generated on 2026-02-15
// Matched: 158, Unmatched: 4, Skipped: 118

export const EXERCISE_GIF_MAP = {
  "c-bench-flat-bb": "https://static.exercisedb.dev/media/EIeI8Vf.gif", // barbell bench press (145)
  "c-bench-flat-db": "https://static.exercisedb.dev/media/SpYC0Kp.gif", // dumbbell bench press (115)
  "c-bench-incline-bb": "https://static.exercisedb.dev/media/3TZduzM.gif", // barbell incline bench press (105)
  "c-bench-incline-db": "https://static.exercisedb.dev/media/8eqjhOl.gif", // dumbbell palms in incline bench press (80)
  "c-bench-decline-bb": "https://static.exercisedb.dev/media/DotAgEF.gif", // barbell reverse grip decline bench press (105)
  "c-bench-decline-db": "https://static.exercisedb.dev/media/SpYC0Kp.gif", // dumbbell bench press (80)
  "c-fly-flat-db": "https://static.exercisedb.dev/media/yz9nUhF.gif", // dumbbell fly (140)
  "c-fly-incline-db": "https://static.exercisedb.dev/media/HYe1ZqR.gif", // dumbbell incline fly on exercise ball (100)
  "c-fly-cable": "https://static.exercisedb.dev/media/aqvSOQE.gif", // cable cross-over revers fly (100)
  "c-pushup": "https://static.exercisedb.dev/media/I4hDWkc.gif", // push-up (95)
  "c-pushup-diamond": "https://static.exercisedb.dev/media/soIB2rj.gif", // diamond push-up (120)
  "c-pushup-incline": "https://static.exercisedb.dev/media/GdMa1ET.gif", // incline scapula push up (55)
  "c-pushup-decline": "https://static.exercisedb.dev/media/arvaszz.gif", // modified push up to lower arms (40)
  "c-pushup-pike": "https://static.exercisedb.dev/media/I4hDWkc.gif", // push-up (45)
  "c-dip-chest": "https://static.exercisedb.dev/media/9WTm7dq.gif", // chest dip (105)
  "c-machine-press": "https://static.exercisedb.dev/media/wDN97Ca.gif", // machine inner chest press (75)
  "c-pec-deck": null, // no match
  "c-landmine-press": "https://static.exercisedb.dev/media/LMGXZn8.gif", // barbell decline close grip to skull press (45)
  "c-svend-press": "https://static.exercisedb.dev/media/I1OBLnn.gif", // weighted svend press (65)
  "c-pullover-db": "https://static.exercisedb.dev/media/9XjtHvS.gif", // dumbbell pullover (110)
  "b-pullup": "https://static.exercisedb.dev/media/lBDjFxJ.gif", // pull-up (105)
  "b-chinup": "https://static.exercisedb.dev/media/T2mxWqc.gif", // chin-up (105)
  "b-pullup-wide": "https://static.exercisedb.dev/media/OYFhXVD.gif", // wide grip rear pull-up (50)
  "b-pullup-neutral": "https://static.exercisedb.dev/media/0V2YQjW.gif", // pull up (neutral grip) (70)
  "b-muscle-up": "https://static.exercisedb.dev/media/yJUHKTn.gif", // muscle up (160)
  "b-row-bb": "https://static.exercisedb.dev/media/SzX3uzM.gif", // barbell reverse grip bent over row (110)
  "b-row-pendlay": "https://static.exercisedb.dev/media/r0z6xzQ.gif", // barbell pendlay row (100)
  "b-row-db": "https://static.exercisedb.dev/media/ZIViNh1.gif", // dumbbell reverse grip incline bench one arm row (110)
  "b-row-cable": "https://static.exercisedb.dev/media/UFGF6gk.gif", // cable rope crossover seated row (110)
  "b-lat-pulldown": "https://static.exercisedb.dev/media/rkg41Fb.gif", // twin handle parallel grip lat pulldown (125)
  "b-lat-pulldown-close": "https://static.exercisedb.dev/media/4LoWllp.gif", // band fixed back close grip pulldown (65)
  "b-straight-arm-pulldown": "https://static.exercisedb.dev/media/x69MAlq.gif", // cable straight arm pulldown (90)
  "b-deadlift-conv": "https://static.exercisedb.dev/media/hrVQWvE.gif", // barbell straight leg deadlift (105)
  "b-deadlift-sumo": "https://static.exercisedb.dev/media/KgI0tqW.gif", // barbell sumo deadlift (100)
  "b-deadlift-trap": "https://static.exercisedb.dev/media/jQGwmxN.gif", // trap bar deadlift (95)
  "b-tbar-row": "https://static.exercisedb.dev/media/BgljGjd.gif", // lever reverse t-bar row (75)
  "b-face-pull": null, // no match
  "b-reverse-fly-db": "https://static.exercisedb.dev/media/yz9nUhF.gif", // dumbbell fly (70)
  "b-reverse-fly-cable": "https://static.exercisedb.dev/media/PQcUlDi.gif", // cable supine reverse fly (70)
  "b-machine-row": "https://static.exercisedb.dev/media/ZqNOWQ6.gif", // lever reverse grip vertical row (50)
  "b-hyperextension": "https://static.exercisedb.dev/media/zhMwOwE.gif", // hyperextension (120)
  "b-superman": "https://static.exercisedb.dev/media/4GqRrAk.gif", // superman push-up (90)
  "b-rack-pull": "https://static.exercisedb.dev/media/za9Ni4z.gif", // barbell rack pull (100)
  "b-meadows-row": "https://static.exercisedb.dev/media/8d8qJQI.gif", // barbell reverse grip incline bench row (50)
  "b-single-arm-pulldown": "https://static.exercisedb.dev/media/U5INZY6.gif", // cable one arm pulldown (70)
  "b-band-pull-apart": "https://static.exercisedb.dev/media/OyoZ3Pu.gif", // leg pull in flat bench (35)
  "b-inverted-row": "https://static.exercisedb.dev/media/bZGHsAZ.gif", // inverted row (120)
  "b-rope-climb": "https://static.exercisedb.dev/media/yaAxcQr.gif", // rope climb (100)
  "l-squat-bb": "https://static.exercisedb.dev/media/RYcV1kH.gif", // barbell squat jump step rear lunge (130)
  "l-squat-front": "https://static.exercisedb.dev/media/Y7YcmIJ.gif", // barbell bench front squat (130)
  "l-squat-goblet": "https://static.exercisedb.dev/media/yn8yg1r.gif", // dumbbell goblet squat (130)
  "l-squat-overhead": "https://static.exercisedb.dev/media/gfk9kD4.gif", // barbell overhead squat (100)
  "l-squat-zercher": "https://static.exercisedb.dev/media/LSTChY9.gif", // barbell zercher squat (125)
  "l-squat-bodyweight": "https://static.exercisedb.dev/media/wfotm7S.gif", // bodyweight drop jump squat (75)
  "l-squat-pistol": "https://static.exercisedb.dev/media/nqs5HGV.gif", // single leg squat (pistol) male (105)
  "l-squat-sissy": "https://static.exercisedb.dev/media/xdYPUtE.gif", // sissy squat (195)
  "l-leg-press": "https://static.exercisedb.dev/media/V07qpXy.gif", // lever alternate leg press (100)
  "l-lunge-db": "https://static.exercisedb.dev/media/RRWFUcw.gif", // dumbbell lunge (95)
  "l-lunge-bb": "https://static.exercisedb.dev/media/t8iSghb.gif", // barbell lunge (145)
  "l-lunge-reverse": "https://static.exercisedb.dev/media/OrETs32.gif", // reverse hyper on flat bench (45)
  "l-lunge-walking": "https://static.exercisedb.dev/media/IZVHb27.gif", // walking lunge (65)
  "l-lunge-curtsy": null, // no match
  "l-leg-ext": "https://static.exercisedb.dev/media/my33uHU.gif", // lever leg extension (95)
  "l-bulgarian": "https://static.exercisedb.dev/media/qx4fgX7.gif", // dumbbell single leg split squat (90)
  "l-hack-squat": "https://static.exercisedb.dev/media/Qa55kX1.gif", // sled hack squat (65)
  "l-step-up": "https://static.exercisedb.dev/media/76vfTdU.gif", // dumbbell step up single leg balance with bicep curl (75)
  "l-belt-squat": "https://static.exercisedb.dev/media/IeDEXTe.gif", // lever seated squat calf raise on leg press machine (45)
  "l-wall-sit": "https://static.exercisedb.dev/media/sVQCCeG.gif", // march sit (wall) (70)
  "l-box-jump": "https://static.exercisedb.dev/media/iPm26QU.gif", // box jump down with one leg stabilization (100)
  "l-broad-jump": "https://static.exercisedb.dev/media/uZKq7lo.gif", // forward jump (50)
  "l-hip-abduction": "https://static.exercisedb.dev/media/CHpahtl.gif", // lever seated hip abduction (95)
  "l-hip-adduction": "https://static.exercisedb.dev/media/oHsrypV.gif", // lever seated hip adduction (90)
  "p-rdl-bb": "https://static.exercisedb.dev/media/wQ2c4XD.gif", // barbell romanian deadlift (100)
  "p-rdl-db": "https://static.exercisedb.dev/media/rR0LJzx.gif", // dumbbell romanian deadlift (120)
  "p-rdl-single": "https://static.exercisedb.dev/media/daBmy1Y.gif", // dumbbell single leg deadlift with stepbox support (65)
  "p-leg-curl": "https://static.exercisedb.dev/media/17lJ1kr.gif", // lever lying leg curl (125)
  "p-nordic-curl": "https://static.exercisedb.dev/media/ANbbry2.gif", // lower back curl (45)
  "p-hip-thrust": "https://static.exercisedb.dev/media/qKBpF7I.gif", // barbell glute bridge (50)
  "p-glute-bridge": "https://static.exercisedb.dev/media/aWedzZX.gif", // glute bridge two legs on bench (male) (125)
  "p-glute-kickback": "https://static.exercisedb.dev/media/HEJ6DIX.gif", // cable kickback (120)
  "p-donkey-kick": "https://static.exercisedb.dev/media/v7p5bYl.gif", // kick out sit (45)
  "p-fire-hydrant": "https://static.exercisedb.dev/media/WL4EmxJ.gif", // side bridge hip abduction (45)
  "p-clamshell": null, // no match
  "p-good-morning": "https://static.exercisedb.dev/media/JrOHAZc.gif", // barbell stiff leg good morning (105)
  "p-calf-raise-stand": "https://static.exercisedb.dev/media/ykUOVze.gif", // lever standing calf raise (125)
  "p-calf-raise-seat": "https://static.exercisedb.dev/media/bOOdeyc.gif", // lever seated calf raise (125)
  "p-calf-raise-bw": "https://static.exercisedb.dev/media/bJYHBIN.gif", // bodyweight standing calf raise (75)
  "p-calf-raise-single": "https://static.exercisedb.dev/media/1kB3Wmk.gif", // dumbbell single leg calf raise (70)
  "s-ohp-bb": "https://static.exercisedb.dev/media/kTbSH9h.gif", // barbell seated overhead press (95)
  "s-ohp-db": "https://static.exercisedb.dev/media/znQUdHY.gif", // dumbbell seated shoulder press (105)
  "s-arnold-press": "https://static.exercisedb.dev/media/Xy4jlWA.gif", // dumbbell arnold press (95)
  "s-push-press": "https://static.exercisedb.dev/media/FS63wTN.gif", // dumbbell push press (70)
  "s-machine-press": "https://static.exercisedb.dev/media/wDN97Ca.gif", // machine inner chest press (55)
  "s-lateral-raise": "https://static.exercisedb.dev/media/AQ0mC4Y.gif", // dumbbell full can lateral raise (90)
  "s-lateral-raise-cable": "https://static.exercisedb.dev/media/goJ6ezq.gif", // cable lateral raise (110)
  "s-front-raise": "https://static.exercisedb.dev/media/xMjBKwn.gif", // dumbbell lateral to front raise (90)
  "s-front-raise-plate": "https://static.exercisedb.dev/media/hbY9wqG.gif", // front lever reps (30)
  "s-upright-row": "https://static.exercisedb.dev/media/RgJDRR1.gif", // barbell wide-grip upright row (90)
  "s-shrug-bb": "https://static.exercisedb.dev/media/dG7tG5y.gif", // barbell shrug (140)
  "s-shrug-db": "https://static.exercisedb.dev/media/NJzBsGJ.gif", // dumbbell shrug (140)
  "s-lu-raise": "https://static.exercisedb.dev/media/6e2DcYX.gif", // dumbbell incline shoulder raise (40)
  "s-reverse-pec-deck": "https://static.exercisedb.dev/media/ZqNOWQ6.gif", // lever reverse grip vertical row (30)
  "a-curl-bb": "https://static.exercisedb.dev/media/25GPyDY.gif", // barbell curl (145)
  "a-curl-db": "https://static.exercisedb.dev/media/2JCuFTU.gif", // dumbbell kneeling bicep curl exercise ball (105)
  "a-hammer-curl": "https://static.exercisedb.dev/media/GNhAeJ0.gif", // dumbbell hammer curls (with arm blaster) (100)
  "a-preacher-curl": "https://static.exercisedb.dev/media/bWxq4op.gif", // dumbbell one arm reverse preacher curl (95)
  "a-incline-curl": "https://static.exercisedb.dev/media/ae9UoXQ.gif", // dumbbell incline curl (105)
  "a-cable-curl": "https://static.exercisedb.dev/media/G08RZcQ.gif", // cable curl (115)
  "a-conc-curl": "https://static.exercisedb.dev/media/lyKCLmK.gif", // dumbbell seated revers grip concentration curl (95)
  "a-spider-curl": "https://static.exercisedb.dev/media/VdLZ3nB.gif", // dumbbell one arm reverse spider curl (95)
  "a-reverse-curl": "https://static.exercisedb.dev/media/Y5X65IB.gif", // ez barbell reverse grip curl (110)
  "a-zottman-curl": "https://static.exercisedb.dev/media/kXaIn5A.gif", // dumbbell zottman curl (100)
  "a-curl-21s": "https://static.exercisedb.dev/media/82LxxkW.gif", // barbell wrist curl (45)
  "a-tri-pushdown": "https://static.exercisedb.dev/media/3ZflifB.gif", // cable pushdown (125)
  "a-tri-overhead": "https://static.exercisedb.dev/media/NN8nSNT.gif", // cable rope high pulley overhead tricep extension (125)
  "a-tri-skullcrusher": "https://static.exercisedb.dev/media/yRLPCLu.gif", // barbell reverse grip skullcrusher (95)
  "a-tri-kickback": "https://static.exercisedb.dev/media/wOLmCXc.gif", // dumbbell tricep kickback with stork stance (125)
  "a-close-grip-bench": "https://static.exercisedb.dev/media/gx7s7uF.gif", // barbell incline close grip bench press (130)
  "a-dip-tricep": "https://static.exercisedb.dev/media/bZq4bwK.gif", // weighted tricep dips (105)
  "a-tri-cable-overhead": "https://static.exercisedb.dev/media/NN8nSNT.gif", // cable rope high pulley overhead tricep extension (75)
  "a-dip-machine": "https://static.exercisedb.dev/media/J60bN17.gif", // assisted triceps dip (kneeling) (50)
  "a-wrist-curl": "https://static.exercisedb.dev/media/82LxxkW.gif", // barbell wrist curl (95)
  "a-reverse-wrist-curl": "https://static.exercisedb.dev/media/LsZkfU6.gif", // barbell reverse wrist curl (95)
  "a-farmers-carry": "https://static.exercisedb.dev/media/qPEzJjA.gif", // farmers walk (125)
  "x-plank": "https://static.exercisedb.dev/media/CosupLu.gif", // front plank with twist (125)
  "x-side-plank": "https://static.exercisedb.dev/media/5VXmnV5.gif", // bodyweight incline side plank (100)
  "x-crunch": "https://static.exercisedb.dev/media/QUDd8WS.gif", // oblique crunches floor (125)
  "x-situp": "https://static.exercisedb.dev/media/AR0ig3o.gif", // flexion leg sit up (bent knee) (75)
  "x-leg-raise": "https://static.exercisedb.dev/media/I3tsCnC.gif", // hanging leg raise (175)
  "x-hanging-leg-raise": "https://static.exercisedb.dev/media/I3tsCnC.gif", // hanging leg raise (115)
  "x-russian-twist": "https://static.exercisedb.dev/media/XVDdcoj.gif", // russian twist (150)
  "x-ab-wheel": "https://static.exercisedb.dev/media/xnInPfE.gif", // barbell standing ab rollerout (40)
  "x-cable-crunch": "https://static.exercisedb.dev/media/8xUv4J7.gif", // cable seated crunch (75)
  "x-dead-bug": "https://static.exercisedb.dev/media/iny3m5y.gif", // dead bug (145)
  "x-mountain-climber": "https://static.exercisedb.dev/media/RJgzwny.gif", // mountain climber (140)
  "x-bicycle-crunch": "https://static.exercisedb.dev/media/rbu5UUb.gif", // cross body crunch (130)
  "x-v-up": "https://static.exercisedb.dev/media/H6ETwO9.gif", // band v-up (70)
  "x-flutter-kick": "https://static.exercisedb.dev/media/UVo2Qs2.gif", // flutter kicks (145)
  "x-hollow-hold": "https://static.exercisedb.dev/media/9c6T1YX.gif", // bridge - mountain climber (cross body) (35)
  "x-bird-dog": "https://static.exercisedb.dev/media/01qpYSe.gif", // upward facing dog (40)
  "x-pallof-press": "https://static.exercisedb.dev/media/9pa4H5m.gif", // band horizontal pallof press (105)
  "x-woodchop": "https://static.exercisedb.dev/media/8xUv4J7.gif", // cable seated crunch (50)
  "x-toe-touch": "https://static.exercisedb.dev/media/oLrKqDH.gif", // run (60)
  "x-heel-tap": "https://static.exercisedb.dev/media/qaZVsGk.gif", // alternate heel touchers (50)
  "x-dragon-flag": "https://static.exercisedb.dev/media/pQ0Mx1Z.gif", // flag (95)
  "x-copenhagen-plank": "https://static.exercisedb.dev/media/5VXmnV5.gif", // bodyweight incline side plank (45)
  "x-l-sit": "https://static.exercisedb.dev/media/UpWmA5E.gif", // l-sit on floor (95)
  "x-hanging-windshield": "https://static.exercisedb.dev/media/BaE7O6U.gif", // hanging oblique knee raise (40)
  "o-clean": "https://static.exercisedb.dev/media/SiWCcTN.gif", // power clean (175)
  "o-clean-hang": "https://static.exercisedb.dev/media/SiWCcTN.gif", // power clean (75)
  "o-snatch": "https://static.exercisedb.dev/media/dG5Smob.gif", // snatch pull (100)
  "o-clean-jerk": "https://static.exercisedb.dev/media/vzAxBtt.gif", // kettlebell one arm clean and jerk (70)
  "o-thruster": "https://static.exercisedb.dev/media/f7Y9eDZ.gif", // barbell thruster (95)
  "o-push-jerk": "https://static.exercisedb.dev/media/IMRsOCn.gif", // squat jerk (75)
  "f-kb-swing": "https://static.exercisedb.dev/media/UHJlbu3.gif", // kettlebell swing (120)
  "f-kb-snatch": "https://static.exercisedb.dev/media/aXcUyKb.gif", // kettlebell one arm snatch (70)
  "f-kb-clean-press": "https://static.exercisedb.dev/media/vzAxBtt.gif", // kettlebell one arm clean and jerk (55)
  "f-kb-goblet-squat": "https://static.exercisedb.dev/media/ZA8b5hc.gif", // kettlebell goblet squat (115)
  "f-turkish-getup": "https://static.exercisedb.dev/media/Ha7SZ3y.gif", // kettlebell turkish get up (squat style) (95)
  "f-sled-push": "https://static.exercisedb.dev/media/tj41Nu6.gif", // sled 45в° leg wide press (25)
  "f-sled-pull": "https://static.exercisedb.dev/media/OM46QHm.gif", // cable pull through (with rope) (30)
  "f-tire-flip": "https://static.exercisedb.dev/media/oZjMu1t.gif", // tire flip (120)
};
